### ISSUE TITLE
Model loading error: FileNotFoundException: endreborn:models/item/tool_ender_bow_pulling_2.json

### ISSUE THREAD

**Issue by LemADEC** [EleC0TroN/EndReborn#3]
As of EndReborn [0.1.7], a file is missing, causing model loading errors:
```
[10:33:14] [main/ERROR] [FML]: Could not load override model endreborn:item/tool_ender_bow_pulling_2 for model endreborn:models/item/ender_bow
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model endreborn:item/tool_ender_bow_pulling_2 with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:203) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.getDependencies(ModelLoader.java:373) [ModelLoader$VanillaModelWrapper.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:174) [ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:304) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:175) [cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:153) [ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.FileNotFoundException: endreborn:models/item/tool_ender_bow_pulling_2.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:334) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1600(ModelLoader.java:117) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:870) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 17 more
```

**Comment by EleC0TroN** [comment]
Yes, I know, and I'm trying to fix it. Error does not cause crash

**Comment by LemADEC** [comment]
it causes a lot of spam in console, makes harder to find other issues that may impact the server.
Keep up the good work on the mod :)

**Comment by EleC0TroN** [comment]
Done
