### ISSUE TITLE
Recipes JSON parsing error for endreborn:armors/armour boots obsidian

### ISSUE THREAD

**Issue by LemADEC** [EleC0TroN/EndReborn#4]
As of EndReborn [0.1.7], a recipe file is malformed, causing errors at boot:
```
[10:33:26] [main/ERROR] [FML]: Parsing error loading recipe endreborn:armors/armour boots obsidian
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 2 column 1 path $
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:494) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:707) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:667) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_162]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:619) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.EOFException: End of input at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[TypeAdapters$35$1.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	... 17 more
```

**Comment by EleC0TroN** [comment]
This is because of an extra file I forgot to delete
